services:
  concierge:
    image: infosecinnovations/concierge:latest
    container_name: concierge
    environment:
      - OPENSEARCH_HOST=opensearch-node1
      - OLLAMA_HOST=ollama
    ports:
      - ${WEB_PORT:-15130}:15130
    restart: unless-stopped